### PR TITLE
Make code follow coding standard more closely

### PR DESCRIPTION
**Pull request by MikeMatrix**

### CODE REVIEW

**Comment by AACO** [comment]
Indentation looks good, brace formatting is still off though.

**Comment by MikeMatrix** [comment]
Haven't worked on that yet. Are we using the same standard for braces that ACE3 uses?

**Comment by AACO** [comment]
Probably?

**Comment by MikeMatrix** [comment]
Resolved merge conflict here. Should be ready for review, unless we want to adapt some other things for coding standards.
I don't think we need a whole lot for coding standards, just because of the nature of the project.

**Pull request merged**
